### ISSUE TITLE
company-jedi vs jedi

### ISSUE THREAD

**Issue by hisnawi** [emacsorphanage/company-jedi#21]
So I first installed jedi and found it very useful and nice, it includes full function arguments.

Then I read that if I have company already then I should install company-jedi. I already use company/irony/clang for C++. So I deleted jedi and jedi-core and installed company-jedi instead. Unfortunately, all I see now with completion is function names and no full parameters like when jedi was installed. Am I missing something?

I am also pleased with eldoc integration with irony/company. But I can't seem to make it work with python. Is there special setup I need to include?

**Comment by nabajour** [comment]
It might be that the problem with not getting the full parameter list is not a company-jedi issue but a jedi-core issue.

I had the same, trying to use jedi.el instead showed me that the issue was present in there also. 

Using manual function to show parameters (type a function like `os.open` and then run `M-x jedi:get-in-function-call`) got me a message like this:
`error "\"AttributeError(\\\"'Definition' object has no attribute 'get_code'... blablabla...`

It looks like its linked to these issues in jedi: [#294](https://github.com/tkf/emacs-jedi/pull/294) and [#296](https://github.com/tkf/emacs-jedi/pull/296)

Applying the changes by hand to `jediepcserver.py` and reinstalling the jedi server fixed the issue here.

**Comment by philiparvidsson** [comment]
What's the status here? Why isn't PR being merged?

**Comment by SergiyKolesnikov** [comment]
`company-jedi` still requires `jedi-core` (which you deleted).

**Comment by gonewest818** [comment]
duplicated by #24, closing this one and redirecting the discussion to the other ticket.
